services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      # Mount only source/assets to keep container node_modules intact
      - ./apps/web/src:/usr/src/app/src
      - ./apps/web/public:/usr/src/app/public
      # Mount Next config read-only so edits don't require an image rebuild (dev restart still needed)
      - ./apps/web/next.config.js:/usr/src/app/next.config.js:ro

  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api/src:/usr/src/app/src
      - ./apps/api/prisma:/usr/src/app/prisma
